### ISSUE TITLE
Feature Request - add configurable option to prevent deletion instead of just warning

### ISSUE THREAD

**Issue by tom-d8** [dawoe/umbraco-nexu#22]
It would be useful to have a configurable option to prevent deletion of used items, rather than just a warning. Users would then have to replace the referenced item before they could delete it.

Another option would be to allow only Admin users to delete the item but Editors would not have that option, as above, they would have to change references to items first

TIA
t

**Comment by dawoe** [comment]
Hi @tom-d8 

This has been fixed in the lastest beta release. Would be nice if you could test it.

You can add these app settings to your web.config

`<add key="nexu:PreventDelete" value="true" />`
`<add key="nexu:PreventUnPublish" value="true" />`

Leaving them out or setting them to false enables deleting and unpublishing
